---
### provision AWS VPC
- hosts: localhost
  connection: local
  
    
  tasks:
    # To get the vpc_id

    - name: Create VPC
      ec2_vpc_net:
       
        region: us-west-2
        name: vpc_name 
        cidr_block: 172.22.0.0/16
        state: "present"
      register: my_vpc
    # Create the subnet
    # associate the subnet to the vpc
    # we map_public to yes this means -
    # all instance created in this subnet will have a public IP address.
    - name: create and associate subnet with VPC.
      ec2_vpc_subnet:
        state: present
        
        vpc_id: "{{ my_vpc.vpc.id }}"
        region: us-west-2
        cidr: 172.22.0.0/16
        map_public: yes
        resource_tags:
          Name:  public_subnet_name
      register: subnet

    # Create Internet gateway.
    # assign with the vpc.
    # all instance in this vpc will have access to the internet.
    - name: Create IGW
      ec2_vpc_igw:
        vpc_id: "{{ my_vpc.vpc.id }}"
        state: present
      
        region: us-west-2
        tags:
          Name: igw_name
      register: igw

    - name: Route IGW
      ec2_vpc_route_table:
     
        vpc_id: "{{ my_vpc.vpc.id }}"
        region: us-west-2
        subnets:
          - "{{ subnet.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
        tags:
          Name: route_name
