---
- name:  IAM user Creation
  hosts: localhost
  gather_facts: False
  tasks:
     - name: Task # Launch IAM Group

       iam:

          iam_type: user
          aws_access_key: "AKIA43FCT556UDAZXTVT"
          aws_secret_key: "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"
          name: "username"
          state: "present"
          password: "userpassword"
          access_key_state: create
       register: iam
