---
- name:  IAM user Creation
  hosts: localhost
  gather_facts: False
  tasks:
     - name: Task # Launch IAM Group

       iam:

          iam_type: user
          aws_access_key: "AKIA43FCT556YV67SHNA"
          aws_secret_key: "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"
          name: "username"
          state: "present"
          password: "userpassword"
          access_key_state: create
       register: iam
