---
- name:  IAM user Creation
  hosts: localhost
  gather_facts: False
  tasks:
     - name: Task # Launch IAM Group

       iam:

          iam_type: user
          aws_access_key: "accesskey"
          aws_secret_key: "secretkey"
          name: "username"
          state: "present"
          password: "userpassword"
          access_key_state: create
       register: iam
