---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Sample Template AutoScalingMultiAZWithNotifications:
  Create a multi-az, load balanced and Auto Scaled sample web site running '
Parameters:
  VpcId:
    Type: String
    Description: VpcId of your existing Virtual Private Cloud (VPC)
 
  Subnets:
    Type: List<String>
    Description: The list of SubnetIds in your Virtual Private Cloud (VPC)
  #Subnet2:
   # Type: List<String>
    #Description: The list of SubnetIds in your Virtual Private Cloud (VPC)
Resources:
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
        Ref: Subnets
        #Ref: Subnet2
  
