AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  LatestAmiId:
    Description: Region specific image from the Parameter Store
    Type: String
    Default: ami
  InstanceType:
    Description: Amazon EC2 instance type for the instances
    Type: String
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
    Default: "instancetype"
  VpcId:
    Type: String
    Default: "vpcid"
    Description: VpcId of your existing Virtual Private Cloud (VPC)
 
  Subnets:
    Type: List<String>
    Default: "twosubnets"
Resources:
  myLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateName: "LaunchTemplateName1"
      LaunchTemplateData:
        ImageId: !Ref LatestAmiId
        InstanceType: !Ref InstanceType
  myASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref myLaunchTemplate
        Version: !GetAtt myLaunchTemplate.LatestVersionNumber
      MaxSize: 'MaxSize1'
      MinSize: 'MinSize1'
      DesiredCapacity: 'DesiredCapacity1'
      VPCZoneIdentifier: 'VPCZoneIdentifier1'
