---
- name:  provisioning EC2 instances volume using Ansible
  hosts: localhost
  gather_facts: False
  
  tasks:
     - name:  Launch the new EC2 Instance volume
       ec2-vol:
          instance: "{{ instnceid }}"
          Volume_type: "{{ Volume_type1}}"
          volume_size: "{{ volume_size1 }}"
          wait: true
          #count: "{{ count1 }}"
          device_name: /dev/xvdf
         # keypair: "{{ keypair1 }}"
          #Availability_Zone: "{{ Availability_Zone1 }}"
          #snapshot: "{{ snapshot1 }}"
       register: ec2-vol
