---
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  LatestAmiId:
    Description: Region specific image from the Parameter Store
    Type: String
    Default: amiId
  InstanceType:
    Description: Amazon EC2 instance type for the instances
    Type: String
    Default: instancetype
  
Resources:
  myLaunchConfig: 
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: 
         !Ref LatestAmiId      
      InstanceType: 
        !Ref InstanceType
      
