---
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  LatestAmiId:
    Description: Region specific image from the Parameter Store
    Type: String
    Default: default1
  InstanceType:
    Description: Amazon EC2 instance type for the instances
    Type: String
    Default: deafault2
Resources:
  myLaunchConfig: 
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: 
        !Ref InstanceType
      
