---
AWSTemplateFormatVersion: 2010-09-09
Description: "AWS CloudFormation Sample Template
  EC2InstanceWithSecurityGroupSample: Create an Amazon EC2 security group for the instance to give you SSH access.
Parameters:
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: "9"
    MaxLength: "18"
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "fromport"
          ToPort: "toport"
          CidrIp:
            Ref: SSHLocation
