---
AWSTemplateFormatVersion: '2010-09-09'
Description: Create Elastic File System v20161029-1200
Parameters:
  # EFS
  PerformanceMode:
    Type: String
    Default: generalPurpose
    AllowedValues:
    - generalPurpose
    - maxIO
Resources:
  FileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      FileSystemTags:
      - Key: Name
        Value: !Ref AWS::StackName
      PerformanceMode: !Ref PerformanceMode
  
Outputs:
  FileSystem:
    Description: FileSystem
    Value: !Ref FileSystem
  PerformanceMode:
    Description: PerformanceMode
    Value: !Ref PerformanceMode
