AWSTemplateFormatVersion: 2010-09-09
Parameters:
  PerformanceMode:
    Type: String
    Default: generalPurpose
    AllowedValues:
    - generalPurpose
    - maxIO
Resources:
  MountTargetVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.31.0.0/16
 
  MountTargetSubnetOne:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 172.31.1.0/24
      VpcId: !Ref MountTargetVPC
      AvailabilityZone: "AvailabilityZone1"
 
  FileSystemResource:
    Type: 'AWS::EFS::FileSystem'
    Properties:
      AvailabilityZoneName: AvailabilityZone1
      BackupPolicy:
        Status: ENABLED
      Encrypted: Encrypted1
      LifecyclePolicies:
        - TransitionToIA: LifecyclePolicies1
        - TransitionToPrimaryStorageClass: LifecyclePolicies2
      FileSystemTags:
      - Key: Name
        Value: !Ref AWS::StackName
      PerformanceMode: !Ref PerformanceMode

  MountTargetResource1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystemResource
      SubnetId: !Ref MountTargetSubnetOne
      SecurityGroups:
      - !GetAtt MountTargetVPC.DefaultSecurityGroup
 
  
